const { chromium } = require(resolvePlaywright());
function resolvePlaywright() { for (const c of ['playwright', '/home/claude/.npm-global/lib/node_modules/playwright', '/opt/node-tools/node_modules/playwright', '/usr/lib/node_modules/playwright']) { try { require.resolve(c); return c; } catch (e) { } } throw new Error('playwright not found; npm i -g playwright'); } const http=require('http'); const fs=require('fs'); const path=require('path');
const root=require('path').join(__dirname,'site'); const server=http.createServer((req,res)=>{let p=decodeURIComponent(req.url.split('?')[0]); if(p==='/admin/'||p==='/admin')p='/admin/index.html'; const f=path.join(root,p); if(!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);res.end();return;} const t={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json'}[path.extname(f)]||'text/plain'; res.writeHead(200,{'content-type':t}); res.end(fs.readFileSync(f));});
(async()=>{ await new Promise(r=>server.listen(4174,r)); const b=await chromium.launch().catch(()=>chromium.launch({executablePath:'/opt/pw-browsers/chromium'})); const page=await b.newPage({viewport:{width:1360,height:950}});
 const errors=[]; page.on('pageerror',e=>errors.push('PAGEERROR '+e.message)); page.on('console',m=>{ if(m.type()==='error' && !/Failed to load resource/.test(m.text())) errors.push('CONSOLE '+m.text()); });
 await page.route(/gstatic|googleapis|jsdelivr|cdnjs/, r=>r.abort());
 await page.goto('http://localhost:4174/admin/'); await page.waitForTimeout(900);
 const shot=async n=>page.screenshot({path:path.join(__dirname,`shot2-${n}.png`)});
 const nav=async p=>{ const sel=`.nav-links a[data-page="${p}"]`; await page.$eval(sel,el=>el.scrollIntoView({block:'center'})); await page.waitForTimeout(100); await page.click(sel,{force:true}); await page.waitForTimeout(400); };
 const out={};
 await nav('costing-home'); await shot('home'); out.marginRows = await page.$$eval('#page-costing-home .c-table-sm tbody tr', r=>r.length);
 await nav('costing-products'); await shot('products'); out.productCards = await page.$$eval('#page-costing-products .c-card', r=>r.length);
 await page.click('[data-action="edit-product"][data-id="celebration-cake"]'); await page.waitForTimeout(400); await shot('product-modal');
 out.sizeCards = await page.$$eval('#costing-modal [data-size-idx]', r=>r.length);
 // change 6-inch labor hours to 2 and save
 await page.fill('#costing-modal [data-size-idx="0"] [data-s="laborHours"]', '2'); await page.click('[data-action="save-product"]'); await page.waitForTimeout(400);
 out.after6h = await page.$eval('#page-costing-products', el=>el.innerText.match(/6-inch round[^\n]*/)?.[0]);
 await nav('costing-estimator'); await page.waitForTimeout(500);
 await page.selectOption('#est-add-product','celebration-cake'); await page.click('[data-action="est-add-item"]'); await page.waitForTimeout(400);
 await page.selectOption('[data-tier="0:0"] [data-tf="sizeId"]','8'); await page.waitForTimeout(400);
 await page.selectOption('[data-tier="0:0"] [data-tf="fillingRecipeId"]','ganache'); await page.waitForTimeout(400);
 await page.check('[data-i="drip"]'); await page.waitForTimeout(400);
 await page.fill('[data-i="fondantFigures"]','2'); await page.$eval('[data-i="fondantFigures"]', el=>el.dispatchEvent(new Event('change',{bubbles:true}))); await page.waitForTimeout(400);
 await page.click('[data-action="est-add-tier"]'); await page.waitForTimeout(400);
 await page.selectOption('[data-e="requestId"]','09012026-AB12'); await page.waitForTimeout(400);
 await shot('estimator');
 out.breakdown = (await page.textContent('.c-bd-totals')).replace(/\s+/g,' ').trim();
 out.name = await page.$eval('[data-e="name"]', el=>el.value);
 await page.click('[data-action="est-save"]'); await page.waitForTimeout(500);
 await nav('costing-estimates'); await shot('estimates'); out.estimateRows = await page.$$eval('#page-costing-estimates tbody tr', r=>r.map(x=>x.innerText.replace(/\s+/g,' ')));
 await page.click('[data-action="est-open"]'); await page.waitForTimeout(500); out.reopenedItems = await page.$$eval('#page-costing-estimator .c-est-item', r=>r.length);
 await nav('costing-settings'); await shot('settings'); out.pricingFields = await page.$$eval('#page-costing-settings [id^="p-"]', r=>r.length);
 // cupcakes + cookies quick check
 await nav('costing-estimator'); await page.click('[data-action="est-clear"]').catch(()=>{}); await page.waitForTimeout(300);
 await page.selectOption('#est-add-product','sugar-cookies'); await page.click('[data-action="est-add-item"]'); await page.waitForTimeout(300);
 await page.selectOption('#est-add-product','cupcakes'); await page.click('[data-action="est-add-item"]'); await page.waitForTimeout(300);
 out.mixed = (await page.textContent('.c-bd-totals')).replace(/\s+/g,' ').trim();
 await page.setViewportSize({width:390,height:844}); await page.waitForTimeout(300); await shot('mobile-estimator'); out.scrollW = await page.evaluate(()=>document.documentElement.scrollWidth);
 out.errors=errors; console.log(JSON.stringify(out,null,2)); await b.close(); server.close(); })().catch(e=>{console.error(e);process.exit(1);});
